#!/usr/bin/env bash
# Display information about subdomains dns
domain_information () {
	line=$(dig "$2"."$1"| grep -A1 'ANSWER SECTION:' | tr -d '\n')
	extract=$(echo "$2 $line" | awk '{print "The subdomain " $1 " is a " $7 " record and points to " $8}')
	echo "$extract"
}

if [ $# -eq 1 ]
then
	domain_information "$1" "www"
	domain_information "$1" "lb-01"
	domain_information "$1" "web-01"
	domain_information "$1" "web-02"
elif [ $# -eq 2 ]
then
	domain_information "$1" "$2"
fi
