#!/usr/bin/env bash
#Transfers a file from our client to a server
path= echo -n `pwd` | sed 's/$/\//g'; echo $1
if (($# == 4));
	then 
		scp -i "$4"  -o StrictHostKeyChecking=no "$path" "$3"@"$2":/home/
else
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
fi
