#!/usr/bin/env bash
# Configures the new Ubuntu machine to run nginx
# Nginx should listen through port 80
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo 'Hello World!' > /var/www/html/index.html
