#!/usr/bin/env bash
# Configure your Nginx server to have a custom 404 page

apt-get update
apt-get install -y nginx

mkdir /etc/nginx/html
touch /etc/nginx/html/index.html
echo "Hello World!" > /etc/nginx/html/index.html
touch /etc/nginx/html/404.html
echo "Ceci n'est pas une page" > /etc/nginx/html/404.html

config="}\n\terror_page 404 /404.html;
	location /404 {
      		root /etc/nginx/html;
      		internal;
    	}" 
sed -i "s/}/$config/" /etc/nginx/sites-available/default

service nginx restart
