#!/usr/bin/env bash
# Configure your Nginx server to have a custom 404 page

apt-get update
apt-get install -y nginx

mkdir /etc/nginx/html
touch /etc/nginx/html/index.html
echo "Hello World!" > /etc/nginx/html/index.html
touch /etc/nginx/html/404.html
echo "Ceci n'est pas une page" > /etc/nginx/html/404.html
config="server_name _;\n\n\tlocation \/redirect_me {\n\t\treturn 301 https:\/\/www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n\n\terror_page 404 \/404.html;\n\tlocation \/404 {\n\t\troot \/etc\/nginx\/html;\n\t\tinternal;\n\t}" 
sed -i "s/server_name _;/$config/" /etc/nginx/sites-available/default

service nginx restart
