#!/usr/bin/env bash
# Install and configure HAproxy on a server
# to distribute requests using roundbin algorithm
apt-get update
apt-get install haproxy=2.8.\*

echo "ENABLED=1" >> /etc/default/haproxy

printf %s "frontend my-front-end
	mode http
	bind *:80
	default_backend my-servers
backend my-servers
	balance roundrobin
	server 56698-web-01 3.85.1.5:80 check
	server 56698-web-02 54.237.43.12:80 check
" >> /etc/haproxy/haproxy.cfg

service haproxy restart
