#!/usr/bin/env bash
# Backs up all the databases and tables inside
# and creates an archive
mysqldump --all-databases -u root --password="$1" > backup.sql
filename=`date +"%d-%m-%Y"`
tar -czvf "$filename.tar.gz" backup.sql
