#!/usr/bin/env bash
# Debugs a container for a bug so as it
# connects on port 80
rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
