#!/usr/bin/env bash
#Creates file /var/run/myscript.pid containing its PID
#Display "To infinity and beyond" indefinitely
#Display "I hate the kill command" when receiving a SIGTERM signal
#Display "Y U no love me?!" when receiving a SIGINT signal
#Deletes the file /var/run/myscript.pid and terminates itself when receiving a SIGQUIT or SIGTERM.

echo "$$" > /var/run/myscript.pid

while true
do
	echo "To infinity and beyond"
	sleep 2
	trap 'echo "Y U no love me?!"' SIGINT
	trap 'echo "I hate the kill command" && rm /var/run/myscript.pid; exit' SIGTERM
	trap 'rm /var/run/myscript.pid; exit' SIGQUIT
done
