#!/usr/bin/env bash
#Displays "bad luck" for the 4th and "good luck" for the 8th "Best School" for the other iterations.

i=1

while (( i < 11 ))
do
	if [ $i -eq 4 ]
		then echo "bad luck"
	elif [ $i -eq 8 ]
		then echo "good luck"
	else
		echo "Best School"
	fi
	(( i++ ))
done
