#!/usr/bin/env bash
#Displays numbers from 1 to 20 and add bad luck texts for 4, 9 and 17.

i=1
while [ $i -lt 21 ]
do
	echo "$i"
	if [ $i -eq 4 ]
		then echo "bad luck from China"
	elif [ $i -eq 9 ]
		then echo "bad luck from Japan"
	elif [ $i -eq 17 ]
		then echo "bad luck from Italy"
	fi
	((i += 1))
done

