#!/usr/bin/env bash
# Run Nginx with the nginx user with all active ports listening on 8080
sed -i "s/#user www-data;/user nginx;/" /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
chmod 644 /etc/nginx/nginx.conf
sudo -u nginx service nginx start
